### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by venturis-ventis** [dhyces/wart-decay#1]
Tested with only wart-decay and its dependencies in /.minecraft/mods/
Crash log here: [2022-11-22-3.log](https://github.com/dhyces/wart-decay/files/10070394/2022-11-22-3.log)

**Comment by dhyces** [comment]
Gonna be driving for a few hours, I'll check it out when I can

**Comment by dhyces** [comment]
Fixed in 1.0.1. Sorry about that
